### ISSUE TITLE
Not able to open Back Camera(CAMERA_FACE_REAR) dirctly.

### ISSUE THREAD

**Issue by Kintanpatel4393** [florent37/CameraFragment#10]
final Configuration.Builder builder = new Configuration.Builder();
        builder.setCamera(Configuration.CAMERA_FACE_REAR);

        final CameraFragment cameraFragment = CameraFragment.newInstance(builder.build());
        getSupportFragmentManager().beginTransaction()
                .replace(R.id.content, cameraFragment, FRAGMENT_TAG)
                .commit();
Not work .

**Comment by florent37** [comment]
oh yes, it should work on https://github.com/florent37/CameraFragment/commit/a7dc19664f671159e9e4166185b58dc0d054935f

I'm working on other changes too and will submit a new release 👍

**Comment by mgursch** [comment]
This is not working wit 1.0.3

**Comment by florent37** [comment]
It was working on my device, what's yours ? And what's the API ?

**Comment by mgursch** [comment]
Sorry its not working on my devices

Galaxy S6
Nexus 7 (1. and 2. gen)
Nexus 5X

Whats your device?

I start with rear camera configuration  -  got the callback onCurrentCameraBack - but image is from front camera

**Comment by florent37** [comment]
Mine is nexus 6p, on marshmallow, I will try on 5x

**Comment by Kintanpatel4393** [comment]
i have just update library but still it no work ,i checked in Motorola G3.
But i found some trick Solucation just add this line `  cameraFragment.switchCameraTypeFrontBack();`    in 
```
  public void onCameraSetupForPhoto() {
                    flashSwitchView.setVisibility(View.VISIBLE);
                    cameraFragment.switchCameraTypeFrontBack();  // switch  camera
                }

```

**Comment by mgursch** [comment]
I also used this workaround, but its not really nice.

Library should handle this correctly.

**Comment by amosyuen** [comment]
Also doesn't work for me on Samsung Galaxy S5

**Comment by mbernier85** [comment]
This bug is still valid, I'm using a Moto G4 plus on Marshmallow, and the only to make the rear camera work is to add the switch button, and you actually need to tap it 2 times to make it work.

I will try to send you a pull request when I find the issue.
