### ISSUE TITLE
Nexus 7 crash

### ISSUE THREAD

**Issue by mgursch** [florent37/CameraFragment#12]
Hey
I got a crash on first nexus 7 device. it has no back camera - only front camera

Crashlog
 java.lang.RuntimeException: Unable to start activity ComponentInfo{at.rosenbauer.emerec.mobile/at.rosenbauer.emerec.feed.feed.photovideo.CapturePhotoVideoActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Integer.equals(java.lang.Object)' on a null object reference
02-14 08:53:31.563 17915-17915/? W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
02-14 08:53:31.563 17915-17915/? W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
02-14 08:53:31.563 17915-17915/? W/System.err:     at android.app.ActivityThread.access$900(ActivityThread.java:154)
02-14 08:53:31.563 17915-17915/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
02-14 08:53:31.563 17915-17915/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
02-14 08:53:31.563 17915-17915/? W/System.err:     at android.os.Looper.loop(Looper.java:135)
02-14 08:53:31.563 17915-17915/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5294)
02-14 08:53:31.563 17915-17915/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
02-14 08:53:31.563 17915-17915/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
02-14 08:53:31.563 17915-17915/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
02-14 08:53:31.563 17915-17915/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
02-14 08:53:31.563 17915-17915/? W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Integer.equals(java.lang.Object)' on a null object reference
02-14 08:53:31.563 17915-17915/? W/System.err:     at com.github.florent37.camerafragment.internal.controller.impl.Camera1Controller.switchCamera(Camera1Controller.java:105)
02-14 08:53:31.563 17915-17915/? W/System.err:     at com.github.florent37.camerafragment.internal.ui.BaseAnncaFragment.setCameraTypeFrontBack(BaseAnncaFragment.java:436)
02-14 08:53:31.563 17915-17915/? W/System.err:     at com.github.florent37.camerafragment.internal.ui.BaseAnncaFragment.onViewCreated(BaseAnncaFragment.java:270)
02-14 08:53:31.563 17915-17915/? W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1314)
02-14 08:53:31.563 17915-17915/? W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
02-14 08:53:31.563 17915-17915/? W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
02-14 08:53:31.563 17915-17915/? W/System.err:     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757)
02-14 08:53:31.563 17915-17915/? W/System.err:     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355)
02-14 08:53:31.563 17915-17915/? W/System.err:     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
02-14 08:53:31.563 17915-17915/? W/System.err:     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
02-14 08:53:31.563 17915-17915/? W/System.err:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008)
02-14 08:53:31.564 17915-17915/? W/System.err:     at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
02-14 08:53:31.564 17915-17915/? W/System.err:     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
02-14 08:53:31.564 17915-17915/? W/System.err:     at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
02-14 08:53:31.564 17915-17915/? W/System.err:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
02-14 08:53:31.564 17915-17915/? W/System.err:     at android.app.Activity.performStart(Activity.java:6006)
02-14 08:53:31.564 17915-17915/? W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2321)
02-14 08:53:31.564 17915-17915/? W/System.err: 	... 10 more

**Comment by florent37** [comment]
can you try on the 1.0.3 please ?

**Comment by mgursch** [comment]
Hi

its working on Nexus 7 now. Thanks
