### ISSUE TITLE
Front camera image mirrored

### ISSUE THREAD

**Issue by Onwa1kenobi** [florent37/CameraFragment#42]
When i take an image with the front facing camera, the resulting preview activity displays a rotated, mirrored version of the image. How can i get the exact image as is when image is taken like the rear camera.

**Comment by DesignQu** [comment]
Hello, is the rotation problem solved?

**Comment by Onwa1kenobi** [comment]
Nope, it hasn't been solved.

**Comment by DesignQu** [comment]
It can only get to the rotation angle, manually rotate the picture

**Comment by Onwa1kenobi** [comment]
@DesignQu How would i do that before passing to the preview activity?

**Comment by DesignQu** [comment]
After taking the photo, and then manually turn the photo down?

**Comment by DesignQu** [comment]
I use the source code reference, try to modify its source
