### ISSUE TITLE
onPhotoTaken not called in Fragment

### ISSUE THREAD

**Issue by DamienOvianet** [florent37/CameraFragment#5]
Hi, 

First of all great work for the library !
I've an issue, using cameraFragment in a fragment of mine.

I'm setting my cameraFragment like this:
```
final CameraFragment cameraFragment = CameraFragment.newInstance(new Configuration.Builder().build());

        getChildFragmentManager().beginTransaction()
                .replace(R.id.content, cameraFragment, "camera")
                .addToBackStack(null)
                .commit();
```

It's all looking great and the camera view is ok, but when i want to take a photo using the following code:

```
cameraFragment.takePhotoOrCaptureVideo(new CameraFragmentResultListener() {
                    @Override
                    public void onVideoRecorded(String filePath) {
                        Log.d("PhotoOrVideo","onVideoRecorded");
                    }

                    @Override
                    public void onPhotoTaken(byte[] bytes, String filePath) {
                        Log.d("PhotoOrVideo","onPhotoTaken");
                    }
                });
```
I don't get anything and neither onPhotoTaken or onVideoRecorded is called.
What is strange is i get log, saying it's all working great:

> onRecordStatePhoto
> Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found
> I/OMXClient: MuxOMX ctor
> I/OMXClient: MuxOMX ctor
> D/Camera2Manager: onCaptureCompleted: 
> D/Camera2Manager: onPhotoSuccessFinish: 
> D/Camera2Manager: onCaptureCompleted: 
> D/Camera2Manager: onPhotoSuccessFinish: 

Is the issue comming from libwvm.so ? Looking into your code, the only way I can get onPhotoSuccessFinish but no call of onPhotoTaken would be for my listener to be null, but I just set it once and don't touch it anymore.

Any idea ?

**Comment by laszlo-galosi** [comment]
In my case, onPhotoTaken called twice in the CameraActivity CameraFragmentResultListener.

**Comment by DamienOvianet** [comment]
I edited "onImageAvailable" from Camera2Manager.java

I replaced
`cameraPhotoListener.onPhotoTaken(bytes, outputPath, callback);`
by
`callback.onPhotoTaken(bytes, outputPath.getPath());`

which did the trick to me.

**Comment by Punith1234** [comment]
@DamienOvianet we're also facing same issue .. can share complete code on how you solved it

**Comment by DamienOvianet** [comment]
@Punith1234 As wrote above, i juste updated Camera2Manager.java to force the use of the callback "onPhotoTaken" instead of the one from the listener.

To do so I downloaded the whole library in my project without using gradle.

**Comment by dstarchevskyy** [comment]
@Punith1234 Hey, has you published you changed? Can I use your gradle dependency? 
I just don't like to include all this project to my project...
Thanks!

**Comment by florent37** [comment]
yes it's included in the last version

**Comment by pourya0111** [comment]
@DamienOvianet  hello dude i'm looking for some ways to using this library on fragment but no chance can you please help me?
